"""create user

Revision ID: d1bb13e296d7
Revises: 
Create Date: 2024-01-09 23:56:44.951873

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd1bb13e296d7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('major')
    op.drop_table('User')
    op.drop_table('课程体系')
    op.drop_table('Core_Courses')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Core_Courses',
    sa.Column('course_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('course_no', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255), nullable=True),
    sa.Column('course_name', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255), nullable=False),
    sa.Column('major_name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('credit', mysql.TINYINT(), autoincrement=False, nullable=True),
    sa.Column('semester', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('course_model', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255), server_default=sa.text("''"), nullable=True, comment='专业教育：包括部类核心课，专业核心课，个性化选修课；'),
    sa.Column('gn_model', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255), server_default=sa.text("''"), nullable=True),
    sa.PrimaryKeyConstraint('course_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('课程体系',
    sa.Column('model_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('gn_model', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('course_model', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('else', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('model_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('User',
    sa.Column('user_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255), nullable=True),
    sa.Column('password', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255), nullable=True),
    sa.Column('last_login', mysql.DATETIME(), nullable=True),
    sa.Column('role', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255), server_default=sa.text("'0'"), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('major',
    sa.Column('专业编号', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('培养大类', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255), nullable=True),
    sa.Column('招生大类', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('所属学院（系）', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('培养专业', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255), nullable=True),
    sa.Column('学位', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('专业编号'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
